import Head from 'next/head'
import { Montserrat, Asap, Assistant } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const montserrat = Montserrat({
  weight: '800',
  subsets: ['latin'],
})

const asap = Asap({
  weight: '400',
  subsets: ['latin'],
})

const assistant = Assistant({
  weight: '400',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Number Three Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <h1 className={montserrat.className}>Number Three Studio</h1>
        <h2 className={asap.className}>Tech for Humans</h2>
        <p className={assistant.className}>
          We are a group of engineers who create applications for non-profit purposes. Check back in this space in 2024 for the lauch of appOne, a unique tool for social sciences researchers seeking to gather research data from patients. This app places accessibility and ease of use for patients at the forefront of our design, enabling research into conditions that are often a challenge to researchers' efforts to gather data.
        </p>
        <p className={assistant.className}>
          For more information, or if you would like to get involved, please email <a href="mailto:erin@numberthree.studio" className={styles.link}>erin@numberthree.studio</a>.
        </p>
      </main>
    </>
  )
}
